name: app
description: "Your open second brain powered by Claude AI with integrated voice recording"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # HTTP & WebSocket
  dio: ^5.4.0
  web_socket_channel: ^3.0.0

  # Navigation
  go_router: ^14.0.0

  # Markdown
  flutter_markdown: ^0.7.0

  # Storage
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0

  # Utilities
  uuid: ^4.4.0
  collection: ^1.18.0
  http: ^1.2.0
  url_launcher: ^6.3.0
  file_picker: ^8.0.0+1

  # Audio & Recording
  record: ^6.1.2
  just_audio: ^0.9.42

  # Permissions
  permission_handler: ^12.0.0

  # Omi Device Integration
  flutter_blue_plus: ^1.33.6
  flutter_local_notifications: ^17.0.0

  # Audio Codecs (for Omi)
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.3

  # Local Whisper Transcription
  whisper_ggml: ^1.7.0

  # Local LLM for Title Generation
  flutter_gemma: ^0.11.8

  # OTA Firmware Updates
  nordic_dfu: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.3.7

  # Testing
  http_mock_adapter: ^0.6.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/firmware/
    - assets/models/
